enviroment: "local"

timezone: "Europe/Moscow""

qrGen:
    outputDir: "output"
    siteDir: "site"
    tempDir: "temp"

httpServer:
    address: "localhost:10001"
    timeout: 4s
    idleTimeout: 60s