name: QR-gen tests

on:
  push:
    branches:
      - add*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21.5

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=1m ./...
